# Generated by Django 4.1.5 on 2023-01-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_event_options_remove_event_date_select_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers_avatar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
