# Generated by Django 4.1.5 on 2023-01-09 11:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_speakers_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['speaker_name', 'date_select', 'duration']},
        ),
        migrations.AddField(
            model_name='event',
            name='date_select',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers_avatar',
            field=models.ImageField(upload_to='app/images'),
        ),
    ]
