# Generated by Django 4.1.5 on 2023-01-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_options_event_date_select_event_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers_avatar',
            field=models.ImageField(default='', upload_to='app/images'),
        ),
    ]
